# fill in this file and copy to the folder where the jar is

spring:
  datasource:
    url: jdbc:postgresql://<ip>:<port>/<database>
    username: <username>
    password: <password>
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 900KB

auth:
  secret: <secret>
  token:
    header: Authorization
    prefix: Bearer_
    expiration: 2880000 # 8 hours
    expired_value: EXPIRED

