spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/api
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  profiles:
    active:
      - local

server:
  host: http://127.0.0.1
  error:
    include-message: always

auth:
  secret: ${random.value}
