# fill in this file and copy to the folder where the jar is

spring:
  datasource:
    url: jdbc:postgresql://<ip>:<port>/<database>
    username: <username>
    password: <password>
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 900KB
server:
  host: <host>

auth:
  secret: <secret>
  token:
    header: Authorization
    prefix: Bearer_
    expiration: 480
    expired_value: EXPIRED
  verification:
    subject: 2DO Account Verification
    secret: <verification-secret>
    min_exp: 5
    max_exp: 10

mail:
  sendgrid:
    api_key: <sendgrid_api_key>
    identity: <sendgrid_identity_email>
